@rootUrl = http://localhost:8000/

#API LIST

### check server status
GET {{rootUrl}}


##Auth API

###POST NEW user
POST {{rootUrl}}api/v1/auth/register
Content-Type: application/json

{
   
  "fName": "bibek",
  "lName": "hamal",
  "email": "abcd7@bec.com",
  "password": "test",
  "phone": "123456789"
}

###ACTIVATE NEW USER

POST {{rootUrl}}api/v1/auth/activate-user
Content-Type: application/json

{

  "sessionId": "6881bdda889aa42355308a11",
  "t": "d255a3e3-4d28-4724-acd9-a4656db53018"

}


###login user 
POST {{rootUrl}}api/v1/auth/login
Content-Type: application/json

{
   "email":"abcd7@bec.com",
   "password":"test"

}

###get user profile

GET {{rootUrl}}api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY2Q3QGJlYy5jb20iLCJpYXQiOjE3NTMzMzMyNjgsImV4cCI6MTc1MzMzNDE2OH0.GCtoZqKDs59Gi6uu5AthSiGmgJWSFxhZzC73mOBG1x01

