@rootUrl = http://localhost:8000/

#API LIST

### check server status
GET {{rootUrl}}


##Auth API

###POST NEW user
POST {{rootUrl}}api/v1/auth/register
Content-Type: application/json

{
   
  "fName": "bibek",
  "lName": "hamal",
  "email": "b@b.com",
  "password": "test",
  "phone": "123456789"
}
