@rootUrl = http://localhost:8000
# @rootUrl = https://lms-be-zh0y.onrender.com

#API LIST

### check server status
GET {{rootUrl}}


##Auth API

###POST NEW user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
   
  "fName": "bibek",
  "lName": "hamal",
  "email": "b@b.com",
  "password": "test",
  "phone": "123456789"
}

###ACTIVATE NEW USER

POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{

  "sessionId": "6891a83c9ffd2c2ec5b30021",
  "t": "b8683368-5a8e-498e-8afd-df85ca7de673"

}


###login user 
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "bbekhamal26@gmail.com",
   "password":"Bibek@9"

}

###get user profile

GET {{rootUrl}}/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY2Q3QGJlYy5jb20iLCJpYXQiOjE3NTM4Nzg3OTgsImV4cCI6MTc1Mzg3OTY5OH0.zDk-yMms3lT8nK3H7E6oq8T-vjq1Dc3CUNj0fvDgCro

###renew acessJWT
GET {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiZWtoYW1hbDI2QGdtYWlsLmNvbSIsImlhdCI6MTc3MDYwNzQyMiwiZXhwIjoxNzcwNjA4MzIyfQ.uFm408QSrcw_gHY0NMxuAnQD7EDXXWIR_9ozd21ycnA


###generate the otp
POST {{rootUrl}}/api/v1/auth/otp
Content-Type:  application/json 

{
  "email": "bbekhamal26@gmail.com"
}

###reset password
POST {{rootUrl}}/api/v1/auth/reset-password
Content-Type: application/json

{
  "email": "bbekhamal26@gmail.com",
    "password": "Bibek@7",
      "otp":7408

}


###bBOOKS for public
GET {{rootUrl}}/api/v1/books

###get a single book for public
GET {{rootUrl}}/api/v1/books/public/whispers-of-the-ocean


###geting books for adminc
GET {{rootUrl}}/api/v1/books/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiZWtoYW1hbDI2QGdtYWlsLmNvbSIsImlhdCI6MTc3MDYwNzQyMiwiZXhwIjoxNzcwNjA4MzIyfQ.uFm408QSrcw_gHY0NMxuAnQD7EDXXWIR_9ozd21ycnA

###get books
POST {{rootUrl}}/api/v1/books
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiZWtoYW1hbDI2QGdtYWlsLmNvbSIsImlhdCI6MTc3MDYwNzQyMiwiZXhwIjoxNzcwNjA4MzIyfQ.uFm408QSrcw_gHY0NMxuAnQD7EDXXWIR_9ozd21ycnA

{
  "title":"The Flashpoint Paradox",
  "publishedYear":2011,
  "author":"Geoff Johns",
  "thumbnail":"thumbnail",
  "isbn":"1234567856",
  "genre": "comics",
  "availability": true,
  "status": "active",
  "averageRating": 9.9,
  "description": "this is the flash point paradox"
}

### burrow route
POST {{rootUrl}}/api/v1/burrows
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImJiZWtoYW1hbDI2QGdtYWlsLmNvbSIsImlhdCI6MTc3MDYwODcwMSwiZXhwIjoxNzcwNjA5NjAxfQ.mcdaVFD4ZubbIeau0mYV1ZrXgKwt_Yjav-7nCThqhIM

{
  "bookId": "6927a1b66e9271023584c0a3",
  "title":"The Silent Forest",
  "thumbnail":"uploads/silent_forest_2.jpg"
}
