export const bookData = [
  {
    title: "The Silent Forest",
    slug: "the-silent-forest",
    author: "Evelyn Harper",
    thumbnail: "uploads/silent_forest.jpg",
    imageList: ["uploads/silent_forest_1.jpg", "uploads/silent_forest_2.jpg"],
    isbn: 9780143127796,
    genre: "Thriller",
    publishedYear: 2018,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A gripping thriller where a detective uncovers a secret buried deep in the forest.",
    averageRating: 4.3,
    addedBy: { name: "Admin User" },
    lastUpdatedBy: { name: "Admin User" },
  },

  {
    title: "Dreams of Tomorrow",
    slug: "dreams-of-tomorrow",
    author: "Lucas Bennett",
    thumbnail: "uploads/dreams_tomorrow.jpg",
    imageList: ["uploads/dreams_tomorrow_1.jpg"],
    isbn: 9780525536291,
    genre: "Science Fiction",
    publishedYear: 2020,
    availability: false,
    expectedAvailable: "2025-12-10",
    status: "inactive",
    description: "A futuristic tale exploring the boundaries of human consciousness.",
    averageRating: 4.1,
  },

  {
    title: "Whispers of the Ocean",
    slug: "whispers-of-the-ocean",
    author: "Marina Cole",
    thumbnail: "uploads/ocean.jpg",
    imageList: [],
    isbn: 9780062457714,
    genre: "Romance",
    publishedYear: 2017,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A heartfelt love story set along the breathtaking coastlines of New Zealand.",
    averageRating: 3.9,
  },

  {
    title: "The Last Kingdom",
    slug: "the-last-kingdom",
    author: "Adrian Blake",
    thumbnail: "uploads/last_kingdom.jpg",
    imageList: [],
    isbn: 9780345538376,
    genre: "Fantasy",
    publishedYear: 2015,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A high-fantasy epic about a fallen kingdom and the hero destined to save it.",
    averageRating: 4.6,
  },

  {
    title: "Voices in the Rain",
    slug: "voices-in-the-rain",
    author: "Clara Hoyt",
    thumbnail: "uploads/rain.jpg",
    imageList: ["uploads/rain_1.jpg"],
    isbn: 9780307277671,
    genre: "Mystery",
    publishedYear: 2019,
    availability: false,
    expectedAvailable: "2025-12-22",
    status: "inactive",
    description: "An atmospheric mystery revolving around a town haunted by hidden truths.",
    averageRating: 4.0,
  },

  {
    title: "Moonlit Shadows",
    slug: "moonlit-shadows",
    author: "Dylan Reeves",
    thumbnail: "uploads/moon.jpg",
    imageList: [],
    isbn: 9781408855898,
    genre: "Horror",
    publishedYear: 2016,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A spine-chilling horror novel about creatures lurking under the pale moonlight.",
    averageRating: 4.2,
  },

  {
    title: "Echoes of Eternity",
    slug: "echoes-of-eternity",
    author: "Nora Winslow",
    thumbnail: "uploads/eternity.jpg",
    imageList: ["uploads/eternity_1.jpg", "uploads/eternity_2.jpg"],
    isbn: 9781501128035,
    genre: "Fantasy",
    publishedYear: 2014,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A tale of immortals, lost memories, and the journey to reclaim one’s soul.",
    averageRating: 4.5,
  },

  {
    title: "Fragments of Time",
    slug: "fragments-of-time",
    author: "Sean Adler",
    thumbnail: "uploads/time.jpg",
    imageList: [],
    isbn: 9780385537858,
    genre: "Science Fiction",
    publishedYear: 2021,
    availability: false,
    expectedAvailable: "2026-01-05",
    status: "inactive",
    description: "A sci-fi adventure involving time loops, paradoxes, and alternate realities.",
    averageRating: 4.4,
  },

  {
    title: "The Golden Path",
    slug: "the-golden-path",
    author: "Teresa Clarke",
    thumbnail: "uploads/golden_path.jpg",
    imageList: [],
    isbn: 9780143110439,
    genre: "Adventure",
    publishedYear: 2013,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A gripping journey following explorers in search of a legendary treasure.",
    averageRating: 3.8,
  },

  {
    title: "Under the Crimson Sky",
    slug: "under-the-crimson-sky",
    author: "Henry Dalton",
    thumbnail: "uploads/crimson.jpg",
    imageList: [],
    isbn: 9780451490841,
    genre: "Historical Fiction",
    publishedYear: 2018,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A beautiful tale set during wartime about love, survival, and hope.",
    averageRating: 4.7,
  },

  {
    title: "A Dance With Storms",
    slug: "a-dance-with-storms",
    author: "Jasmine Iris",
    thumbnail: "uploads/storms.jpg",
    imageList: [],
    isbn: 9780590353427,
    genre: "Fantasy",
    publishedYear: 2012,
    availability: false,
    expectedAvailable: "2025-12-30",
    status: "inactive",
    description: "A magical world where elemental warriors battle to restore balance.",
    averageRating: 4.1,
  },

  {
    title: "Broken Strings",
    slug: "broken-strings",
    author: "Mia Collins",
    thumbnail: "uploads/strings.jpg",
    imageList: [],
    isbn: 9781250146045,
    genre: "Drama",
    publishedYear: 2019,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A powerful drama about family, forgiveness, and healing old wounds.",
    averageRating: 4.0,
  },

  {
    title: "The Art of Shadows",
    slug: "the-art-of-shadows",
    author: "Caleb Monroe",
    thumbnail: "uploads/shadows.jpg",
    imageList: [],
    isbn: 9780062315007,
    genre: "Mystery",
    publishedYear: 2016,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A detective uncovers a hidden art world filled with dangerous secrets.",
    averageRating: 3.9,
  },

  {
    title: "Beneath the Frozen River",
    slug: "beneath-the-frozen-river",
    author: "Hannah Fielding",
    thumbnail: "uploads/frozen_river.jpg",
    imageList: [],
    isbn: 9780525952251,
    genre: "Thriller",
    publishedYear: 2015,
    availability: false,
    expectedAvailable: "2026-02-14",
    status: "inactive",
    description: "A psychological thriller involving a missing person and a chilling discovery.",
    averageRating: 4.2,
  },

  {
    title: "The Painter's Secret",
    slug: "the-painters-secret",
    author: "Oliver Gray",
    thumbnail: "uploads/painter.jpg",
    imageList: ["uploads/painter1.jpg"],
    isbn: 9780399178573,
    genre: "Literary Fiction",
    publishedYear: 2020,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "An artist hides a life-changing secret in his final masterpiece.",
    averageRating: 4.4,
  },

  {
    title: "Kingdom of Glass",
    slug: "kingdom-of-glass",
    author: "Aria Devlin",
    thumbnail: "uploads/glass.jpg",
    imageList: [],
    isbn: 9781619634480,
    genre: "Fantasy",
    publishedYear: 2014,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A young queen must navigate politics and magic in a fragile glass kingdom.",
    averageRating: 4.5,
  },

  {
    title: "Waves of Serenity",
    slug: "waves-of-serenity",
    author: "Lila Hart",
    thumbnail: "uploads/serenity.jpg",
    imageList: [],
    isbn: 9780399590504,
    genre: "Romance",
    publishedYear: 2019,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A beautiful romance about healing, self-discovery, and second chances.",
    averageRating: 4.0,
  },

  {
    title: "The Forgotten City",
    slug: "the-forgotten-city",
    author: "Ronan Blake",
    thumbnail: "uploads/city.jpg",
    imageList: [],
    isbn: 9780316201643,
    genre: "Adventure",
    publishedYear: 2013,
    availability: false,
    expectedAvailable: "2026-01-10",
    status: "inactive",
    description: "Explorers uncover an ancient city filled with secrets and hidden dangers.",
    averageRating: 3.7,
  },

  {
    title: "Shattered Reflections",
    slug: "shattered-reflections",
    author: "Emily Rhodes",
    thumbnail: "uploads/reflections.jpg",
    imageList: [],
    isbn: 9781501173219,
    genre: "Drama",
    publishedYear: 2018,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A moving story about identity, loss, and rebuilding a broken life.",
    averageRating: 4.3,
  },

  {
    title: "The Clockmaker's Paradox",
    slug: "the-clockmakers-paradox",
    author: "Victor Hale",
    thumbnail: "uploads/clock.jpg",
    imageList: [],
    isbn: 9780307887442,
    genre: "Science Fiction",
    publishedYear: 2022,
    availability: true,
    expectedAvailable: null,
    status: "active",
    description: "A brilliant clockmaker discovers a device that can alter the flow of time.",
    averageRating: 4.6,
  },
];
